import type { Metadata } from "next";
import "./globals.css";

// Layout components
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="flex flex-col h-screen font-primary"
      >
      <Header />
        <div className="flex-grow">
          {children}
        </div>
      <Footer />
      </body>
    </html>
  );
}
